// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTDvXWaxCQonL4_aBXlUzHx8DFG7JOPFI',
    appId: '1:1081285997349:web:26bd48a795ec1c111420cc',
    messagingSenderId: '1081285997349',
    projectId: 'pneumoscanai-256f5',
    authDomain: 'pneumoscanai-256f5.firebaseapp.com',
    storageBucket: 'pneumoscanai-256f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA64d1h11UORkqBnwhl_CjonR3-vEfveKg',
    appId: '1:1081285997349:android:ac7483bf2da916bc1420cc',
    messagingSenderId: '1081285997349',
    projectId: 'pneumoscanai-256f5',
    storageBucket: 'pneumoscanai-256f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu5eyBg3uCZ0CfuGAlsxKxk3-VXHwMttI',
    appId: '1:1081285997349:ios:86218ca5eb083b011420cc',
    messagingSenderId: '1081285997349',
    projectId: 'pneumoscanai-256f5',
    storageBucket: 'pneumoscanai-256f5.firebasestorage.app',
    iosBundleId: 'com.example.pneumoniaDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu5eyBg3uCZ0CfuGAlsxKxk3-VXHwMttI',
    appId: '1:1081285997349:ios:86218ca5eb083b011420cc',
    messagingSenderId: '1081285997349',
    projectId: 'pneumoscanai-256f5',
    storageBucket: 'pneumoscanai-256f5.firebasestorage.app',
    iosBundleId: 'com.example.pneumoniaDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTDvXWaxCQonL4_aBXlUzHx8DFG7JOPFI',
    appId: '1:1081285997349:web:7c4b609e845d40931420cc',
    messagingSenderId: '1081285997349',
    projectId: 'pneumoscanai-256f5',
    authDomain: 'pneumoscanai-256f5.firebaseapp.com',
    storageBucket: 'pneumoscanai-256f5.firebasestorage.app',
  );
}
